export interface MetadataTraits {
    [trait: string]: string[];
}

export interface CollectionMetadata {
    [collection: string]: MetadataTraits;
}

const METADATA_TRAITS: CollectionMetadata = {
    "rebbits": {
        "Backdrop": [
            "Ash Grey.png",
            "BTC.png",
            "Backseat.PNG",
            "Backyard.png",
            "Beach.png",
            "Blue.png",
            "Blushing Magenta.png",
            "COSMIC.png",
            "Clockwork.png",
            "Concrete.png",
            "Corner.PNG",
            "Cream Puff.png",
            "Denim.png",
            "Desert2.png",
            "Desert.PNG",
            "Dusty.png",
            "Exotic Moth.png",
            "Flaming Red.png",
            "Garden.PNG",
            "Gloomy.png",
            "Hall.PNG",
            "Kim Seok-jin.png",
            "Kitchen.PNG",
            "Lavender Haze.png",
            "Moss.png",
            "Mountains.PNG",
            "Mushy Land.PNG",
            "Mystic Mauve.png",
            "Oblivion.png",
            "Olive Jar.png",
            "Olympus.png",
            "Orange Peel.png",
            "Peppermint.png",
            "Pilar.png",
            "Pink.png",
            "Planet Anemone.PNG",
            "Planet Magenta.PNG",
            "Planet Savana.PNG",
            "Planet Vivid.PNG",
            "Planet.png",
            "Playground.PNG",
            "Rocky Road.PNG",
            "Soba.png",
            "Sprout.png",
            "Star Space.png",
            "Strawberry Milkshake.png",
            "Street Side.PNG",
            "Sunrise.png",
            "Sunset.png",
            "Sunshine.png",
            "The Hills.PNG",
            "Trip.PNG",
            "Tropical.PNG",
            "Valley.png",
            "Washed Denim.png",
            "Watchtower.png",
            "za.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png"
        ],
        "Body": [
            "Autobot.png",
            "Blueprint.png",
            "Camouflage.png",
            "Chestnut.png",
            "Chief.png",
            "Cotton.png",
            "Cybernetic.png",
            "Dark X-Ray.png",
            "Droid.png",
            "Labubu.png",
            "Midnight.png",
            "Mischief.png",
            "Mutant.png",
            "Plushie.png",
            "Shadow.png",
            "Slimy Jelly.png",
            "Sunny.png",
            "Voltachu.png",
            "Wild.png",
            "Wine.png",
            "X-Ray.png"
        ],
        "Clothing": [
            "Athlete.png",
            "Autobot.png",
            "Cosmonaut.png",
            "Ghouls.png",
            "Golfer.png",
            "Herbs Farmer.png",
            "Homeboy.png",
            "Kacchu.png",
            "Knight.png",
            "Magician.png",
            "Ninja.png",
            "Pilot.png",
            "Pirate.png",
            "Reaper.png",
            "Rider.png",
            "Scarecrow.png",
            "Sheriff.png",
            "Space Ranger.png",
            "Summer.png",
            "Tribe Chief.png",
            "Varsity.png",
            "Winter.png",
            "Wizard.png",
            "za.png",
            "zb.png",
            "zc.png"
        ],
        "Eyes": [
            "Angry.png",
            "Autobot.png",
            "Button.png",
            "Classic Shade.png",
            "Confused.png",
            "Cosmos Reflectors.png",
            "Cybernetic.png",
            "D. Scars.png",
            "Evil.png",
            "Grumpy.png",
            "Hypnotized.png",
            "Intense.png",
            "K.O..png",
            "Mad.png",
            "Neon Glaze.png",
            "Owl.png",
            "Please.png",
            "Retro Frames.png",
            "Sad.png",
            "Salty.png",
            "Scared.png",
            "Silly.png",
            "Sixth Sense.png",
            "Sleep Mask.png",
            "Sparkly.png",
            "Stoned.png",
            "Sus.png",
            "Sweet.png",
            "Vintage Rounder.png",
            "rabbits.png",
            "za.png",
            "zaa.png",
            "zab.png",
            "zac.png",
            "zad.png",
            "zae.png",
            "zaf.png",
            "zag.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png",
            "zo.png",
            "zp.png",
            "zq.png",
            "zr.png",
            "zs.png",
            "zt.png",
            "zu.png",
            "zv.png",
            "zw.png",
            "zx.png",
            "zy.png",
            "zz.png"
        ],
        "Hand": [
            "a.png",
            "b.png",
            "c.png",
            "d.png",
            "e.png",
            "f.png",
            "g.png",
            "h.png",
            "i.png",
            "j.png",
            "k.png",
            "l.png",
            "m.png",
            "n.png",
            "o.png",
            "p.png",
            "q.png",
            "r.png",
            "s.png",
            "t.png",
            "u.png",
            "v.png",
            "w.png",
            "x.png",
            "y.png",
            "z.png",
            "za.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png",
            "zo.png",
            "zp.png",
            "zq.png",
            "zr.png",
            "zs.png",
            "zt.png"
        ],
        "Head": [
            "Athlete Sweatband.png",
            "Boxing Headguard.png",
            "Chief Pride.png",
            "Cosmonaut.png",
            "Cowboy.png",
            "Durag.png",
            "FUD Hat.png",
            "Headphone.png",
            "Jack O' Lantern.png",
            "Kabuto.png",
            "Knight Armor.png",
            "Magician.png",
            "Megamind.png",
            "Mutant Ninja.png",
            "Pilot.png",
            "Pirate.png",
            "Pizza.png",
            "Poser Cap.png",
            "Runner Knot.png",
            "Shaman Veil.png",
            "Snorkle.png",
            "Straw Hat.png",
            "Wizard.png",
            "za.png",
            "zaa.png",
            "zab.png",
            "zac.png",
            "zad.png",
            "zae.png",
            "zaf.png",
            "zag.png",
            "zah.png",
            "zai.png",
            "zaj.png",
            "zak.png",
            "zal.png",
            "zam.png",
            "zan.png",
            "zao.png",
            "zap.png",
            "zaq.png",
            "zar.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png",
            "zo.png",
            "zp.png",
            "zq.png",
            "zr.png",
            "zs.png",
            "zt.png",
            "zu.png",
            "zv.png",
            "zw.png",
            "zx.png",
            "zy.png",
            "zz.png"
        ],
        "Mouth": [
            "Amazed.png",
            "Angry.png",
            "Bearded.png",
            "Blah.png",
            "Bunny.png",
            "Cheeky Mockery.png",
            "Classic Buck.png",
            "Exhausted.png",
            "Frown.png",
            "Grimacing.png",
            "Imperial.png",
            "Lopsided.png",
            "Nonchalant.png",
            "Pipe.png",
            "Playful.png",
            "Poker Face.png",
            "Raging.png",
            "Shifu.png",
            "Shocked.png",
            "Smoky.png",
            "Spite.png",
            "Stitched.png",
            "Surprised.png",
            "Unimpressed.png",
            "za.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png",
            "zo.png",
            "zp.png",
            "zq.png",
            "zr.png",
            "zs.png",
            "zt.png",
            "zu.png",
            "zv.png",
            "zw.png",
            "zx.png",
            "zy.png"
        ],
        "Speciality": [
            "Bulls Pierce.png",
            "Electro.png",
            "Geo.png",
            "Golf Club.png",
            "Herbs Farm.png",
            "Hydro.png",
            "Mystic.png",
            "Pierce.png",
            "Rage.png",
            "Straw Stem.png",
            "z.png",
            "za.png",
            "zb.png",
            "zc.png",
            "zd.png",
            "ze.png",
            "zf.png",
            "zg.png",
            "zh.png",
            "zi.png",
            "zj.png",
            "zk.png",
            "zl.png",
            "zm.png",
            "zn.png"
        ]
    },
    "odds-wizard": {
        "Background": [
            "Cosmos.png",
            "Daylight.png",
            "Denim.png",
            "Dungeon.png",
            "Dust.png",
            "Epigraph.png",
            "Graphite.png",
            "Grey.png",
            "Hall.png",
            "Lab.png",
            "Land.png",
            "Larva.png",
            "Lavender.png",
            "Matcha.png",
            "Midnight.png",
            "Mystic Forest.png",
            "Ocean.png",
            "Salmon.png",
            "Strawberry.png",
            "Sunkist.png",
            "Sunset.png",
            "Violet.png",
            "White.png",
            "Yellow.png"
        ],
        "Skin": [
            "Alien.png",
            "Bone.png",
            "Clown.png",
            "Croc.png",
            "Devil.png",
            "Drac.png",
            "Elder.png",
            "Elf.png",
            "Fish.png",
            "Flesh.png",
            "Galaxy.png",
            "Golem.png",
            "Ice King.png",
            "Magma.png",
            "Mankind.png",
            "Mummy.png",
            "Night Owl.png",
            "Orc.png",
            "Robot.png",
            "Rune.png",
            "Stitch.png",
            "Tattoo.png",
            "Toy.png",
            "Wukong.png",
            "Yellow.png"
        ],
        "Clothes": [
            "Apocalypse Gear.png",
            "Astrologer.png",
            "Blank.png",
            "Blue Coat.png",
            "Clown.png",
            "Darth Vader.png",
            "Devil.png",
            "Egypt Attire.png",
            "Fighter.png",
            "Give Up.png",
            "Goblin.png",
            "Grim Reaper Coat.png",
            "HAHA!.png",
            "Hippie Attire.png",
            "Holy Suit.png",
            "Jedai Suit.png",
            "Lab Coat.png",
            "Mankind Suit.png",
            "Monk Attire.png",
            "Nature Coat.png",
            "Patched Coat.png",
            "Pirate.png",
            "Robe.png",
            "Seer.png",
            "Shroom Farmer.png",
            "Sloth.png",
            "Stargaze Coat.png",
            "Tie Die.png",
            "Tribal Attire.png",
            "Zeus Suit.png"
        ],
        "Beard": [
            "Alien Dread.png",
            "Colombus.png",
            "Egypt.png",
            "Elder.png",
            "Fire.png",
            "Gems.png",
            "Glaxy.png",
            "Green.png",
            "Grey.png",
            "Hippie.png",
            "Ice King.png",
            "Mankind.png",
            "Nature.png",
            "Obi Wan.png",
            "Professor.png",
            "Spuh.png",
            "Tentacels.png",
            "Tribe.png",
            "Wolf.png",
            "Wukong.png",
            "Zeus.png"
        ],
        "Mustache": [
            "Alien.png",
            "Bad Clown.png",
            "Brown.png",
            "Clown.png",
            "Drac.png",
            "Egypt.png",
            "Elder.png",
            "Galaxy.png",
            "Gandalf.png",
            "Goblin.png",
            "Grey Pade.png",
            "Hippie.png",
            "Ice King.png",
            "Joker.png",
            "Nature.png",
            "On Fire.png",
            "Pade.png",
            "Pipe.png",
            "Scientist.png",
            "Smoke.png",
            "Survival.png",
            "Tentacles.png",
            "Tribe.png",
            "Weird.png",
            "Wukong.png",
            "Zeus.png"
        ],
        "Nose": [
            "Alien.png",
            "Big.png",
            "Clown.png",
            "Damaged.png",
            "Devil.png",
            "Drac.png",
            "Emerald.png",
            "Ice King.png",
            "Magma.png",
            "Mankind G.png",
            "Mankind.png",
            "Mech.png",
            "Pyramid.png",
            "Red.png",
            "Shell.png",
            "Shroom.png",
            "Snotty.png",
            "Tribe.png",
            "Wizard.png",
            "Wood.png",
            "Wukong.png"
        ],
        "Eyes": [
            "Alien.png",
            "Anoyed.png",
            "Brown.png",
            "Bush.png",
            "Clown.png",
            "Devil.png",
            "Egypt.png",
            "Elder.png",
            "Eye Balls.png",
            "Fighter.png",
            "Flame.png",
            "Gods.png",
            "Grumpy.png",
            "Ice King.png",
            "Insane.png",
            "Intense.png",
            "Lightning.png",
            "Scary.png",
            "Sea-Monster.png",
            "Senior.png",
            "Shroom.png",
            "Third Sight.png",
            "Wukong.png"
        ],
        "Head": [
            "8 Bit.png",
            "Alien.png",
            "Astra.png",
            "Blank.png",
            "Blue Hippie.png",
            "Brown Wizard.png",
            "Bull Horn.png",
            "Clown.png",
            "Cone.png",
            "Cosmos Reflectors.png",
            "Darth Vaderr.png",
            "Devil.png",
            "Doflamingo.png",
            "Fire.png",
            "Flame.png",
            "Goblin.png",
            "Greek.png",
            "Green Wizard.png",
            "Grey Wizard.png",
            "Hippie.png",
            "Joker.png",
            "King.png",
            "Mystery Ball.png",
            "Patched Beannie.png",
            "Pirate.png",
            "Pit Vipers.png",
            "Poker Face.png",
            "Polkadot Wizard.png",
            "Purple Wizard.png",
            "Santa.png",
            "Scientist.png",
            "Shroom.png",
            "Skull.png",
            "Stargaze.png",
            "Stars.png",
            "White.png",
            "Wood.png",
            "Wukong.png",
            "Yellow.png"
        ],
        "Hand": [
            "Alien.png",
            "Apocalypse.png",
            "ATOM.png",
            "Babu Pengus.png",
            "Black Hole.png",
            "Blank.png",
            "Blue Lightsaber.png",
            "BNB.png",
            "BTC.png",
            "Chill.png",
            "Clown.png",
            "Devil Fork.png",
            "ETH.png",
            "Flame.png",
            "Goblin Bomb.png",
            "Holy Cross.png",
            "Ice.png",
            "Lightning Bolt.png",
            "Mage.png",
            "Magic Shroom.png",
            "OSMO.png",
            "Parrot.png",
            "Penguin.png",
            "Pharoah.png",
            "Reaper.png",
            "Red Lightsaber.png",
            "Scientist.png",
            "SOL.png",
            "Spellcraft.png",
            "STARS.png",
            "TIA.png",
            "Tribe.png",
            "Trident.png",
            "Weird Weed.png",
            "Wood.png",
            "Wukong.png"
        ]
    }
};

export { METADATA_TRAITS }