nodeLinker: node-modules
supportedArchitectures:
  os: ['linux', 'darwin']
  cpu: ['x64', 'arm64']

# Skip problematic optional dependencies
ignoreDependencies:
  - '@ledgerhq/hw-transport-node-hid'
  - '@ledgerhq/hw-transport-node-hid-noevents'
  - 'node-hid'
